headerAktivitas_deviceSettingsPage: xpath=//p[contains(@class,'mb-4 mt-8')]
linkAturPerangkat_deviceSettingsPage: xpath=//a[contains(@href,'device')]
linkAksesAkun_deviceSettingsPage: xpath=//a[contains(@href,'linking')]
listPerangkat_deviceSettingsPage: xpath=//div[contains(@class,'flex-row p-4')]
tablePerangkat_deviceSetttingPage: xpath=//div[contains(@class,'my-6')]
alertSuccessrRevokeOthers_deviceSettingsPage: xpath=//p[contains(@class,'text-left')]
alertSuccessrRevokeOwn_deviceSettingsPage: xpath=//div[contains(@class,'shadow-md')]
buttonDeleteOwn_deviceSettingsPage: xpath=//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/section[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/button[1]/*[1]
buttonKeluar_deviceSettingsPage: xpath=//button[contains(text(),'Keluar')]
buttonDeleteAnother_deviceSettingPage: xpath=//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/section[1]/div[5]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/button[1]/*[1]
buttonDeleteFullPage_deviceSettingPage: xpath=//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/section[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/button[1]/*[1]
